//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLensFrontEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MovieLensEntities : DbContext
    {
        public MovieLensEntities()
            : base("name=MovieLensEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<GenomeScore> GenomeScores { get; set; }
        public virtual DbSet<GenomeTag> GenomeTags { get; set; }
    
        public virtual ObjectResult<GetUserMoviesRatingsByUserID_Result> GetUserMoviesRatingsByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserMoviesRatingsByUserID_Result>("GetUserMoviesRatingsByUserID", userIDParameter);
        }
    }
}
