//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLensFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public string Tag1 { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
